# Copyright 2020 Konstruktor, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default_stages: [commit, push]
default_language_version:
  python: python3

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black

-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
      - id: bandit
        args: [-lll, -r]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: flake8
        args: ['--config=setup.cfg']

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: insert-license
        name: Add license headers [.py]
        files: \.py$
        types: [python]
        exclude: ^\.tethys/.*$"|^\.github/.*$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - LICENSE.tpl
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license headers [.rst]
        files: \.rst$
        exclude: ^\.tethys/.*$"|^\.github/.*$
        args:
          - --comment-style
          - "||"
          - --license-filepath
          - docs/LICENSE.tpl
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license headers [.sh]
        files: \.sh$
        types: [shell]
        exclude: ^\.tethys/.*$"|^\.github/.*$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - LICENSE.tpl
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license headers [.yaml]
        files: \.yaml$|\.yml$
        types: [yaml]
        exclude: ^\.tethys/.*$"|^\.github/.*$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - LICENSE.tpl
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license headers [.md]
        files: \.md$
        exclude: ^\.tethys/.*$"|^\.github/.*$
        args:
          - --comment-style
          - "<!--|| -->"
          - --license-filepath
          - LICENSE.tpl
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add licence for all other files
        files: ^Dockerfile.*$|\.cfg$|\.conf$|\.ini?$|\.readthedocs$
        exclude: ^\.tethys/.*$"|^\.github/.*$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - LICENSE.tpl
          - --fuzzy-match-generates-todo
